import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import BackButton from "@/Conponents/BackButton";
import RefreshButton from "@/Conponents/RefreshButton";
import ForwardButton from "@/Conponents/ForwardButton";
import URLCheckButton from "@/Conponents/URLCheckButton";
import LoginBtn from "@/Conponents/LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "@/Conponents/LogoutBtn";
import SignUpBtn from "@/Conponents/SignUpBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          {session ? (
            <>
              <span>{session.user.name}</span>
              <LogoutBtn />
            </>
          ) : (
            <>
              <SignUpBtn />
              <LoginBtn />
            </>
          )}
          <BackButton />
          <RefreshButton />
          <ForwardButton />
          <URLCheckButton />
        </div>
        {children}
      </body>
    </html>
  );
}
