import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import BackButton from "@/Conponents/BackButton";
import RefreshButton from "@/Conponents/RefreshButton";
import ForwardButton from "@/Conponents/ForwardButton";
import URLCheckButton from "@/Conponents/URLCheckButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <BackButton />
          <RefreshButton />
          <ForwardButton />
          <URLCheckButton />
        </div>
        {children}
      </body>
    </html>
  );
}
